# Generated by Django 3.2.9 on 2021-12-18 14:37

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
